  language: python
  python:
    - "3.8"
  before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
  install:
    - pip install -r requirements.txt
    - python setup.py install
    - python build.py build_ext --inplace
  script:
    - pytest
